[package]
name = "min-resume"
version = "0.2.0"
description = "Simple and professional résumé for professional people"
entrypoint = "src/lib.typ"
authors = ["Maycon F. Melo <@mayconfmelo>"]
license = "MIT-0"
categories = [ "cv", "office" ]
keywords = [
  "resume", "résumé", "curriculum", "curriculo", "currículo brasileiro"
]
repository = "https://github.com/mayconfmelo/min-resume"
exclude = [
  "dev/",
  "test/",
  "docs/",
  "scripts/",
  ".git",
  ".gitignore",
  "justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
  